In [8]:
# Ensemble models of base,large,eda and DCN

import numpy as np

model = ["base.npy","logits.npy","eda.npy","dcn.npy"]

base = np.load(model[0])
large = np.load(model[1])
eda = np.load(model[2])
dcn = np.load(model[3])
label = np.load("labels.npy")

print(base.shape,label)
maxp = 0
maxw = None
ensemble = None

(4887, 4) [1 3 0 ... 2 2 1]


In [9]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    ex = np.exp(x - np.max(x))
    return ex / np.sum(ex,axis=1,keepdims=True)

base = softmax(base)
large = softmax(large)
dcn = softmax(dcn)
eda = softmax(eda)

In [10]:
for i in range(100000):
    weight = np.random.randint(1,100,size=4)
    w = weight/np.sum(weight)
    value = w[0]*base + w[1]*large + w[2]*eda + w[3]*dcn

    correct = np.mean(np.argmax(value,axis=1)==label)
    if correct > maxp:
        maxp = correct
        maxw = w
        ensemble = value
print("The accuracy is:",maxp,"with the weight:",maxw)

The accuracy is: 0.6687129118068345 with the weight: [0.35416667 0.046875   0.10416667 0.49479167]


In [13]:
import numpy as np

base_preds = (np.argmax(base,axis=1))
ensem_preds = (np.argmax(ensemble,axis=1))

print(base_preds[:20],'\n',ensem_preds[:20],"\n",label[:20])

[1 0 0 3 3 1 3 2 2 1 2 1 2 3 2 1 2 3 3 3] 
 [1 0 0 3 0 1 0 2 2 1 0 1 2 3 2 1 2 3 2 3] 
 [1 3 0 1 2 1 0 2 1 0 0 1 2 2 2 1 2 3 2 3]
